-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying(255) NOT NULL, "description" text NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
